# fly.toml app configuration file generated for mrd-phonebook-backend on 2023-09-09T15:17:54-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mrd-phonebook-backend"
primary_region = "ewr"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
